# Narrative + structured content for the companion site, extracted from the
# finalised dissertation. This is the single source for the non-tabular JSON
# (content.json, taxonomy.json, trends.json, meta.json). No component holds prose;
# it all originates here and is emitted to /data by build_data.py.

LAST_UPDATED = "2026-07-29"
REPO_URL = "https://github.com/ai-rt-c/ai-music-generation-thesis-site"

META = {
    "title": "Artificial Intelligence for Music Generation, Arrangement and Orchestration",
    "subtitle": "A Systematic Review (2020–2025)",
    "author": "ZahraSadat Tahawori",
    "supervisor": "Prof. Dr. Gissel Velarde",
    "university": "IU International University of Applied Sciences",
    "program": "M.Sc. Artificial Intelligence",
    "year": 2026,
    "lastUpdated": LAST_UPDATED,
    "repoUrl": REPO_URL,
    "prisma": {
        "identified": 4521, "transferred": 1083, "afterDedup": 783,
        "titleScreened": 383, "afterAbstract": 146,
        "initiallyIncluded": 113, "afterConsolidation": 112,
        "included": 107, "inDepth": 29,
    },
    "counts": {"included": 107, "inDepth": 29, "topSystems": 9, "trends": 8, "taxonomyDimensions": 4},
    "batchAverages": [
        {"batch": "B1 — Symbolic pop/piano", "quality": 4.3, "overall": 3.3, "leading": "structure / melody"},
        {"batch": "B2 — Symbolic diffusion & control", "quality": 3.9, "overall": 3.4, "leading": "control adherence"},
        {"batch": "B3 — Symbolic language models", "quality": 4.4, "overall": 3.8, "leading": "control / melody"},
        {"batch": "B4 — Foundational audio", "quality": 3.6, "overall": 3.2, "leading": "control adherence"},
        {"batch": "B5 — Recent text-to-music", "quality": 4.0, "overall": 3.6, "leading": "quality / control"},
        {"batch": "B6 — Accompaniment arrangement", "quality": 4.1, "overall": 3.5, "leading": "quality / structure"},
        {"batch": "B7 — Orchestration", "quality": 4.2, "overall": 3.8, "leading": "control adherence"},
    ],
    "citations": {
        "apa": "Tahawori, Z. (2026). Artificial intelligence for music generation, arrangement and orchestration: A systematic review (2020–2025) [Master's thesis, IU International University of Applied Sciences].",
        "bibtex": "@mastersthesis{tahawori2026aimusic,\n  author  = {Tahawori, ZahraSadat},\n  title   = {Artificial Intelligence for Music Generation, Arrangement and Orchestration: A Systematic Review (2020--2025)},\n  school  = {IU International University of Applied Sciences},\n  year    = {2026},\n  type    = {Master's thesis}\n}",
    },
    "downloads": [],
    "figures": [
        {"id": "graphical-abstract", "number": 1, "title": "Graphical abstract", "png": "figures/fig_graphical_abstract.png", "caption": "Graphical abstract summarising the scope, method, analysis and key findings of the review.", "alt": "Overview diagram: scope, PRISMA screening funnel, analysis, key findings and the nine most promising methods."},
        {"id": "prisma", "number": 2, "title": "PRISMA 2020 flow diagram", "png": "figures/fig_prisma.png", "caption": "PRISMA 2020 flow diagram of the review. The synthesis-stage selection of 29 methods is separate from PRISMA eligibility.", "alt": "PRISMA flow: 4,521 records identified, 783 screened, 145 full-text, 112 included, 29 in-depth."},
        {"id": "taxonomy", "number": 3, "title": "Extended taxonomy", "png": "figures/Taxonomy.png", "caption": "Extended taxonomy of AI music generation, arrangement and orchestration (2020–2025), extending Zhu et al. (2023).", "alt": "Four-dimension taxonomy: task, generative paradigm, conditioning modality, data representation."},
        {"id": "year-112", "number": 4, "title": "Included studies per year", "png": "figures/fig_year112.png", "caption": "Included studies per year (n = 112).", "alt": "Bar chart of included studies per year, peaking in 2024."},
        {"id": "task-112", "number": 5, "title": "Included studies by task", "png": "figures/fig_task112.png", "caption": "Included studies by task (n = 112).", "alt": "Bar chart of studies by task; orchestration is the sparsest."},
        {"id": "paradigm-112", "number": 6, "title": "Paradigm across the corpus", "png": "figures/fig_paradigm112.png", "caption": "Generative modelling paradigm across the corpus (n = 112).", "alt": "Bar chart of paradigms across the corpus; Transformer/LLM and diffusion dominate."},
        {"id": "trends-timeline", "number": 7, "title": "Trends timeline", "png": "figures/fig_trends_timeline.png", "caption": "Chronological span of the eight research trends (2020–2025); darker = dominant period.", "alt": "Gantt-style timeline of eight research trends across 2020 to 2025."},
        {"id": "paradigm-29", "number": 8, "title": "Paradigm of the 29 systems", "png": "figures/fig_arch.png", "caption": "Generative modelling paradigm of the 29 evaluated systems (Dimension 2 of the taxonomy).", "alt": "Horizontal bar chart of paradigms among the 29 evaluated systems."},
        {"id": "year-trend-29", "number": 9, "title": "Mean overall score by year", "png": "figures/fig_year.png", "caption": "Mean overall score by year across the evaluated subset (n per year shown).", "alt": "Line chart: mean overall score rising from about 2.8 to 3.8."},
        {"id": "domain", "number": 10, "title": "Symbolic vs audio by dimension", "png": "figures/fig_domain.png", "caption": "Symbolic versus audio systems, average score by dimension.", "alt": "Grouped bar chart comparing symbolic and audio systems across dimensions."},
        {"id": "heatmap", "number": 11, "title": "Batch-average heatmap", "png": "figures/fig_heatmap.png", "caption": "Batch-average scores across the eight evaluation dimensions (darker = higher).", "alt": "Heatmap of batch-average scores across eight dimensions."},
        {"id": "rank", "number": 12, "title": "Overall score by system", "png": "figures/fig_rank.png", "caption": "Overall score by system, coloured by domain; the dashed line marks the 4.0 threshold.", "alt": "Ranked horizontal bar chart of overall scores for the 29 systems."},
    ],
}

CONTENT = {
    "home": {
        "tagline": "A systematic review of how AI learned to generate, arrange and orchestrate music, 2020–2025.",
        "summary": "This companion site presents the final 107-study corpus from a PRISMA 2020 systematic review of AI music generation, arrangement and orchestration. It extends an existing taxonomy, synthesises eight research trends, and reports a structured listening evaluation of a post-inclusion subset of 29 representative systems — nine of which score 4.0 or above. Everything here is drawn from the dissertation and is browsable independently of the PDF.",
        "readingPath": [
            {"label": "About the thesis", "href": "/about-thesis"},
            {"label": "Systematic review", "href": "/systematic-review"},
            {"label": "Taxonomy", "href": "/taxonomy"},
            {"label": "Research trends", "href": "/trends"},
            {"label": "Listening evaluation", "href": "/listening-evaluation"},
            {"label": "29 selected systems", "href": "/systems"},
            {"label": "Discussion", "href": "/discussion"},
        ],
    },
    "aboutThesis": {
        "abstract": "The rapid growth of AI-based music generation, arrangement and orchestration has produced a large and fragmented literature, making it difficult to navigate recent developments and identify the most promising approaches. This thesis addresses that gap through a systematic literature review following the PRISMA 2020 guidelines, covering AI methods published between 2020 and 2025. From 4,521 records identified across six academic databases, 1,083 were transferred to Zotero, 783 unique records remained after deduplication, 383 passed title screening and 146 passed abstract screening. Full-text assessment initially included 113 studies; post-inclusion verification consolidated one duplicate publication version to 112 and reclassified five studies as background, producing the final primary corpus of 107 studies. For each primary study, information on methodology, datasets, musical representations, evaluation procedures, metrics and code availability was extracted into a comprehensive comparison table. The review extends the taxonomy proposed by Zhu et al. (2023), synthesises eight major research trends, and identifies and justifies a post-inclusion subset of 29 representative methods for structured listening analysis.",
        "aim": "To conduct a PRISMA-guided systematic review of AI methods for music generation, arrangement and orchestration, with a focus on developments from 2020 to 2025.",
        "researchQuestions": [
            "How have AI-based methods for music generation, arrangement and orchestration evolved since 2020, particularly with the emergence of transformer and diffusion models?",
            "What are the current dominant trends, most commonly used techniques, datasets and evaluation approaches in this field?",
            "Which approaches demonstrate the most promising results, and what factors contribute to their effectiveness?",
        ],
        "contributions": [
            "An extended taxonomy of AI music systems across four dimensions.",
            "A structured comparison of all 107 verified primary studies.",
            "A synthesis of eight research trends spanning 2020–2025.",
            "A structured listening evaluation of a 29-system post-inclusion subset, presented through a companion website.",
        ],
        "objectives": [
            "Perform a systematic literature review following PRISMA 2020.",
            "Extend the taxonomy of Zhu et al. (2023) with recent models.",
            "Develop a comparison table of key studies (2020–2025).",
            "Analyse major research trends.",
            "Identify and justify the most promising approaches.",
            "Present and analyse selected MIDI/audio examples via an interactive page.",
            "Discuss limitations, challenges and future directions.",
        ],
    },
    "systematicReview": {
        "title": "Systematic review",
        "intro": "The review followed the PRISMA 2020 Statement: identification, screening, eligibility assessment, data extraction and qualitative synthesis.",
        "blocks": [
            {"heading": "Data collection", "body": "Publications were identified through six databases and digital libraries: Google Scholar, IEEE Xplore, ACM Digital Library, SpringerLink, ScienceDirect and arXiv, using a predefined keyword set. The search yielded 4,521 records; owing to platform export restrictions, 1,083 could be exported to Zotero, and after removing 300 duplicates, 783 unique records remained."},
            {"heading": "Study selection", "body": "Of the 783 unique records, title screening retained 383 and abstract screening retained 146 for full-text assessment. Full-text eligibility initially included 113 studies. Two post-inclusion verification steps followed: consolidation of the AccoMontage-3 preprint with the published Structured Multi-Track Accompaniment Arrangement contribution reduced the corpus to 112 publication-level studies, and a later eligibility-consistency audit reclassified five studies as background, producing the final primary corpus of 107 studies. These 113→112 and 112→107 transitions document post-inclusion verification rather than rewriting the original PRISMA screening history."},
            {"heading": "In-depth subset", "body": "After the final 107-study primary corpus was established, 29 systems were selected for in-depth synthesis and listening analysis using five criteria: task coverage (S1), methodological influence (S2), architectural diversity (S3), accessible MIDI/MP3 demonstrations (S4) and temporal spread across 2020–2025 (S5). This is a post-inclusion synthesis subset, not a PRISMA eligibility or exclusion stage; all 107 primary studies remain in the master comparison table."},
            {"heading": "Data analysis", "body": "For each study, authors, year, task, architecture, dataset, representation, evaluation method, metrics, music length, training requirements and code availability were extracted into the master comparison table and analysed qualitatively to identify trends, dominant methodologies, challenges and future directions."},
        ],
    },
    "listeningEvaluation": {
        "intro": "The 29 selected systems were assessed through manual critical listening on eight dimensions rated on a five-point scale. Each system was judged on at least one representative example — a hosted demo where available, or, where none existed, a locally generated output or the results reported in the paper. As the assessment reflects a single listener, ratings are descriptive summaries rather than objective benchmarks, and where authors publish curated examples they bound the best case rather than the average case.",
        "rubric": [
            {"key": "quality", "label": "Audio / rendering quality", "meaning": "Cleanliness and fidelity of the produced sound (absence of noise or artefacts)."},
            {"key": "melody", "label": "Melodic coherence", "meaning": "Sensibility and sense of direction of the melodic line."},
            {"key": "harmony", "label": "Harmonic coherence", "meaning": "Consistency and plausibility of the underlying harmony."},
            {"key": "rhythm", "label": "Rhythmic stability", "meaning": "Steadiness and regularity of the rhythmic pulse."},
            {"key": "structure", "label": "Long-term structure", "meaning": "Presence of large-scale musical form (e.g. verse–chorus, development)."},
            {"key": "control", "label": "Control adherence", "meaning": "Fidelity of the output to the given conditioning (text, chords, melody or target)."},
            {"key": "naturalness", "label": "Naturalness / musicality", "meaning": "Overall musical plausibility and expressive quality."},
            {"key": "overall", "label": "Overall", "meaning": "Overall judgement integrating the preceding dimensions."},
        ],
        "caveat": "Scores are descriptive summaries of a structured listening exercise, not objective performance benchmarks, and are interpreted as such throughout.",
    },
    "discussion": {
        "intro": "The review is interpreted in relation to the three research questions, followed by the limitations of the review and of the field.",
        "rq": [
            {"q": "RQ1 — How have methods evolved since 2020?", "a": "The corpus describes a three-stage evolution: representation engineering (2020–2022), paradigm competition and the language interface (2023), and consolidation around controllable diffusion, foundation models and evaluation (2024–2025). Transformers supplied the representational substrate and the autoregressive token-LM baseline (Jukebox → AudioLM → MusicGen); diffusion arrived as the complementary paradigm, decisive where autoregression was weakest — global structure and fine-grained control. The two now coexist by a division of labour. In the structured listening subset, the mean overall score was approximately 2.8 in 2020 and approximately 3.9 in 2024; the intervening annual means fluctuate, so this is not a monotonic year-by-year increase."},
            {"q": "RQ2 — What are the dominant trends, techniques, datasets and evaluation?", "a": "Eight higher-level trends were synthesised from the 107-study corpus. The largest primary categories are symbolic generation (43 studies) and audio generation (31), followed by arrangement (26) and orchestration (7). The corpus comprises 63 symbolic-domain, 43 audio-domain and one mixed-domain study. Transformer or language-model approaches are most common (40 studies), followed by diffusion (32), VAE (11), hybrid or other (8), GAN (8), RNN/LSTM (5) and flow matching (3). Publication activity is concentrated in 2023 and 2024, which together account for 63 of 107 studies. Evaluation combines objective distributional metrics (notably FAD) with subjective preference and controllability measures, alongside an emerging concern with evaluation validity itself."},
            {"q": "RQ3 — Which approaches are most promising, and why?", "a": "Nine of the 29 evaluated methods scored 4.0 or above: GETMusic and ChatMusician (both 4.5), with MusicLM, MusicGen, StemGen, AccoMontage, Whole-Song Generation, Structured Arrangement and SymphonyNet (all 4.0). Two factors separated them: verifiable controllability — the ability to hear that the output follows its conditioning — and explicit long-term structural planning. Audio fidelity was generally high across the subset and did not differentiate the leaders. The most effective systems treated control and structure as first-class design goals rather than by-products of scale."},
        ],
        "limitationsReview": "Screening was carried out by a single reviewer, introducing a risk of selection bias. Export restrictions on three databases meant only 1,083 of 4,521 records could be exported, so the screened set is broad but not exhaustive. The auditory analysis reflects a single listener and is indicative rather than statistically generalisable; where authors publish curated examples, the ratings bound the best case, and for systems without a public demonstration the assessment relied on reported results.",
        "limitationsField": "Evaluation validity emerged as one of the most pressing challenges: distributional metrics correlate imperfectly with human judgement, and some reported gains do not survive fair comparison. Cultural bias is a second concern, as models trained predominantly on Western music generalise poorly beyond those idioms. Efficiency and latency remain obstacles to interactive use. Two capability gaps recur: convincing sung vocals were absent from every system evaluated, and genuine long-term structure remained difficult except where explicitly planned.",
    },
    "futureDirections": {
        "title": "Future directions",
        "intro": "The results point to several concrete directions, grounded in the review rather than in generic future-work statements.",
        "blocks": [
            {"heading": "The orchestration gap", "body": "Orchestration is the least-served task in the corpus, plausibly because it lacks the large paired datasets that fuelled generation research and because instrument interdependence and timbre resist simple tokenisation. Building such datasets and adapting foundation models to orchestration and arrangement is a promising, under-explored direction."},
            {"heading": "Controllable long-form structure", "body": "The hierarchical and two-stage planning that proved most effective here should be extended toward reliably controllable long-form structure."},
            {"heading": "Preference-aligned objectives", "body": "Carrying the reinforcement-learning-from-human-feedback turn further into music generation could align outputs with listener preference rather than likelihood."},
            {"heading": "Standardised evaluation", "body": "Improved, standardised evaluation that better reflects human musical judgement and addresses cultural coverage would strengthen the field's claims."},
            {"heading": "Sung vocals", "body": "Progress on convincing, intelligible singing — the field's most visible remaining frontier — would broaden applicability beyond instrumental music."},
        ],
    },
    "glossary": [
        {"term": "PRISMA 2020", "definition": "A standard set of guidelines for transparent reporting of systematic reviews, covering identification, screening, eligibility and synthesis."},
        {"term": "Symbolic music", "definition": "Music represented as notes or scores (e.g. MIDI, ABC notation) rather than raw sound."},
        {"term": "Audio-domain music", "definition": "Music represented as raw waveform or spectrogram/codec tokens rather than symbolic notes."},
        {"term": "Transformer AR-LM", "definition": "An autoregressive Transformer language model over music tokens — the dominant neural paradigm across the corpus."},
        {"term": "Diffusion model", "definition": "A generative model that synthesises output by iteratively denoising, offering whole-context generation and step-by-step conditioning."},
        {"term": "VAE", "definition": "A variational autoencoder — a latent-variable model used for structured, controllable representations."},
        {"term": "LLM-based", "definition": "A system built on a general-purpose pretrained large language model adapted to read and write music."},
        {"term": "Foundation model", "definition": "A large model pretrained at scale and reused across tasks, rather than a task-specific architecture."},
        {"term": "Flow matching", "definition": "A generative training objective, positioned as a successor to diffusion, often at lower parameter cost."},
        {"term": "State-space (Mamba)", "definition": "A linear-time sequence backbone offered as an alternative to the Transformer for long sequences."},
        {"term": "Arrangement", "definition": "Generating a backing or accompaniment for a given lead, rather than a whole piece from scratch."},
        {"term": "Orchestration", "definition": "Deciding which instruments play what — from timbre matching to controllable re-orchestration."},
        {"term": "Control adherence", "definition": "How faithfully a system's output follows its conditioning (text, chords, melody or target)."},
        {"term": "Long-term structure", "definition": "Large-scale musical form such as verse–chorus organisation or thematic development."},
        {"term": "FAD", "definition": "Fréchet Audio Distance — a common objective metric comparing generated audio to a reference distribution."},
    ],
    "tips": {
        "domain": {
            "Symbolic": "Music as notes or score (MIDI, ABC notation).",
            "Audio": "Music as raw waveform or audio/codec tokens.",
            "Mixed": "A system spanning both symbolic and audio representations.",
        },
        "task": {
            "Symbolic generation": "Generating music represented as notes or score.",
            "Audio generation": "Generating music represented as waveform or audio tokens.",
            "Arrangement": "Backing or accompaniment for a given lead.",
            "Orchestration": "Choosing instruments; timbre matching or re-orchestration.",
        },
        "paradigm": {
            "Transformer": "Autoregressive Transformer language model over music tokens.",
            "LLM": "A repurposed general-purpose large language model.",
            "Foundation model": "Large model pretrained at scale and reused across tasks.",
            "Diffusion": "Iterative denoising generation with step-by-step conditioning.",
            "VAE": "Variational autoencoder — a latent-variable model.",
            "GAN": "Adversarially trained generator.",
            "Flow matching": "A flow-based generative objective, successor to diffusion.",
            "State-space": "Linear-time sequence backbone (Mamba) alternative to the Transformer.",
            "RNN": "Recurrent network (LSTM/GRU).",
            "Hybrid": "Hybrid or other architecture.",
            "Non-neural": "Rules, search or optimisation rather than a neural generator.",
        },
    },
}

# ---- Taxonomy (4 dimensions) ----
TAXONOMY = [
    {"id": "task", "number": 1, "name": "Task", "summary": "The output domain and problem being solved.", "categories": [
        {"id": "gen-symbolic", "name": "Music generation (symbolic)", "status": "base", "description": "Generating symbolic music (MIDI / score).", "exampleIds": ["89", "312", "324", "327"]},
        {"id": "gen-audio", "name": "Music generation (audio)", "status": "base", "description": "Generating audio (waveform / tokens).", "exampleIds": ["92", "76", "329", "334"]},
        {"id": "arrangement", "name": "Arrangement", "status": "base", "description": "Accompaniment, multi-track and covers.", "exampleIds": ["345", "346", "57", "352"]},
        {"id": "orchestration", "name": "Orchestration", "status": "base", "description": "Instrumentation and re-orchestration.", "exampleIds": ["357", "313", "259"]},
    ]},
    {"id": "paradigm", "number": 2, "name": "Generative modelling paradigm", "summary": "The core generative mechanism, extending Zhu et al. (2023).", "categories": [
        {"id": "non-neural", "name": "Non-neural", "status": "base", "description": "Rules, search, evolutionary methods.", "exampleIds": ["357"]},
        {"id": "rnn", "name": "Autoregressive RNN", "status": "base", "description": "LSTM/GRU recurrence (legacy).", "exampleIds": []},
        {"id": "vae", "name": "VAE", "status": "base", "description": "Latent-variable encoding.", "exampleIds": ["346", "259"]},
        {"id": "gan", "name": "GAN", "status": "base", "description": "Adversarial training.", "exampleIds": []},
        {"id": "transformer", "name": "Transformer AR-LM", "status": "base", "description": "Autoregressive music tokens.", "exampleIds": ["89", "309", "312", "313", "76", "329"]},
        {"id": "diffusion", "name": "Diffusion", "status": "expanded", "description": "Latent, discrete and cascaded diffusion.", "exampleIds": ["62", "57", "58", "327", "334", "378"]},
        {"id": "masked", "name": "Masked-token LM", "status": "new", "description": "Non-autoregressive infilling.", "exampleIds": ["352"]},
        {"id": "flow", "name": "Flow matching", "status": "new", "description": "Continuous flow objectives.", "exampleIds": ["379"]},
        {"id": "llm", "name": "LLM-based", "status": "new", "description": "General-purpose pretrained LLMs.", "exampleIds": ["316"]},
        {"id": "foundation", "name": "Foundation models", "status": "new", "description": "Large-scale pretraining, cross-cutting.", "exampleIds": ["74"]},
        {"id": "ssm", "name": "State-space (Mamba)", "status": "new", "description": "Linear-time sequence models.", "exampleIds": ["382"]},
    ]},
    {"id": "conditioning", "number": 3, "name": "Conditioning input modality", "summary": "How the user steers generation.", "categories": [
        {"id": "attribute", "name": "Attribute / parameter", "status": "base", "description": "Structured metadata and control signals.", "exampleIds": ["315"]},
        {"id": "text", "name": "Text", "status": "base", "description": "Natural-language prompts.", "exampleIds": ["76", "329", "324", "378"]},
        {"id": "visual", "name": "Visual", "status": "base", "description": "Image / video input (outside review scope).", "exampleIds": []},
        {"id": "audio-cond", "name": "Audio", "status": "new", "description": "Vocals, stems, reference audio.", "exampleIds": ["349", "352"]},
        {"id": "symbolic-cond", "name": "Symbolic", "status": "new", "description": "Melody, lead sheet, score.", "exampleIds": ["346", "259", "57"]},
    ]},
    {"id": "representation", "number": 4, "name": "Data representation", "summary": "How music is encoded.", "categories": [
        {"id": "symbolic-rep", "name": "Symbolic", "status": "base", "description": "MIDI, event tokens (REMI, compound), ABC, matrix forms.", "exampleIds": ["89", "309", "57"]},
        {"id": "audio-rep", "name": "Audio", "status": "base", "description": "Raw waveform, mel-spectrogram, discrete codec tokens.", "exampleIds": ["92", "328", "76"]},
    ]},
]

# ---- Trends (8) ----
TRENDS = [
    {"id": "t1", "number": 1, "name": "Tokenization and structure-aware representation engineering",
     "periodLabel": "2020–2022 (dominant); persists thereafter", "span": {"start": 2020, "end": 2022, "seedStart": 2020},
     "coreIdea": "Injecting musical structure into the token vocabulary — metre, polyphony, track identity — proved cheaper and more effective than redesigning the network.",
     "whyItMatters": "Representation choice was a substantive scientific question whose answers became the field's shared infrastructure.",
     "representativeIds": ["89", "309", "326", "313", "312", "83", "317"]},
    {"id": "t2", "number": 2, "name": "Controllability as a persistent research axis",
     "periodLabel": "2020 seeds; dominant 2022–2025", "span": {"start": 2022, "end": 2025, "seedStart": 2020},
     "coreIdea": "Control migrates from the latent space, to the training objective, and finally to the sampling process of a frozen model.",
     "whyItMatters": "Controllability turns generation systems into usable creative tools and is the property most consistently evaluated.",
     "representativeIds": ["375", "314", "315", "354", "378", "48", "49"]},
    {"id": "t3", "number": 3, "name": "Paradigm evolution: from autoregressive tokens to iterative refinement",
     "periodLabel": "2020–2025, in three stages", "span": {"start": 2020, "end": 2025},
     "coreIdea": "Autoregression discretises and streams; diffusion offers whole-context, non-causal generation with control; flow matching and state-space backbones emerge as successors. The result is a division of labour, not replacement.",
     "whyItMatters": "This evolution supplies the generative machinery of the entire second half of the corpus.",
     "representativeIds": ["92", "328", "329", "62", "332", "57", "334", "379"]},
    {"id": "t4", "number": 4, "name": "Language as the interface: text-to-music and LLM-based composition",
     "periodLabel": "2023–2025", "span": {"start": 2023, "end": 2025},
     "coreIdea": "Language enters first as the conditioning signal, then as the model itself — importing dialogue, reasoning and tool use into composition.",
     "whyItMatters": "Language collapsed the entry barrier to music generation and imported interactive workflows into composition.",
     "representativeIds": ["76", "58", "324", "378", "360", "316", "280", "364"]},
    {"id": "t5", "number": 5, "name": "Large-scale pretraining and music foundation models",
     "periodLabel": "understanding-first from 2021; generation 2024–2025", "span": {"start": 2024, "end": 2025, "seedStart": 2021},
     "coreIdea": "The unit of progress shifts from the task-specific architecture to the reusable pretrained checkpoint — understanding first, generation second.",
     "whyItMatters": "It changes what counts as a contribution and sets the field's working assumptions at the review's endpoint.",
     "representativeIds": ["311", "321", "365", "74", "65", "30", "322"]},
    {"id": "t6", "number": 6, "name": "Arrangement matures: from accompaniment to stem-aware co-creation",
     "periodLabel": "2020–2025, shift around 2023", "span": {"start": 2020, "end": 2025, "seedStart": 2020},
     "coreIdea": "Arrangement moves from autonomous accompaniment to responding to material a human actually provides — audio, vocals, existing stems.",
     "whyItMatters": "Arrangement is where the corpus moves most decisively toward assistive, context-aware musicianship.",
     "representativeIds": ["345", "346", "351", "349", "352", "19", "20"]},
    {"id": "t7", "number": 7, "name": "Orchestration: from optimization to neural modeling",
     "periodLabel": "2021–2025; the smallest, most thesis-specific trend", "span": {"start": 2021, "end": 2025},
     "coreIdea": "Orchestration recapitulates the field's evolution — optimisation, representation engineering, controllable deep models — but compressed, delayed and under-populated.",
     "whyItMatters": "It establishes the clearest research gap in the corpus, directly motivating this thesis's orchestration focus.",
     "representativeIds": ["357", "359", "313", "259"]},
    {"id": "t8", "number": 8, "name": "Efficiency, alignment, and evaluation maturity",
     "periodLabel": "2024–2025, with a 2020 precursor", "span": {"start": 2024, "end": 2025, "seedStart": 2020},
     "coreIdea": "Once capability was established, research turned inward — making generation fast (non-autoregressive, distillation), aligned (RLHF) and measurable (benchmarking, bias analysis).",
     "whyItMatters": "Deployment, alignment and measurement validity jointly determine whether reported progress is real and usable.",
     "representativeIds": ["78", "337", "340", "338", "383", "374", "373", "376"]},
]
